=== dsanvaz2103/UD4_LMSGI/Act4.2/Mejora.dtd
<!ELEMENT concesionario (coche+)>
<!ELEMENT coche (marca, modelo, matricula, potencia, plazas, puertas, combustible)>
<!ATTLIST coche codigo CDATA #REQUIRED>

<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT puertas (#PCDATA)>
<!ELEMENT combustible (#PCDATA)>

=== dsanvaz2103/UD4_LMSGI/Act4.3/MejoraConcesionario/ConcesionarioMejorado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "..\..\Act4.2\Mejora.dtd">
<concesionario>
    <coche codigo="001">
        <marca>Toyota</marca>
        <modelo>Corolla</modelo>
        <matricula>ABC123</matricula>
        <potencia>120hp</potencia>
        <plazas>5</plazas>
        <puertas>4</puertas>
        <combustible>Gasolina</combustible>
    </coche>
    <coche codigo="002">
        <marca>Honda</marca>
        <modelo>Civic</modelo>
        <matricula>XYZ789</matricula>
        <potencia>150hp</potencia>
        <plazas>5</plazas>
        <puertas>4</puertas>
        <combustible>Diesel</combustible>
    </coche>
    <coche codigo="003">
        <marca>BMW</marca>
        <modelo>M5</modelo>
        <matricula>UIO789</matricula>
        <potencia>250hp</potencia>
        <plazas>5</plazas>
        <puertas>4</puertas>
        <combustible>Gasolina</combustible>
    </coche>
    <coche codigo="004">
        <marca>Mercedes</marca>
        <modelo>Benz</modelo>
        <matricula>UII879</matricula>
        <potencia>350hp</potencia>
        <plazas>5</plazas>
        <puertas>4</puertas>
        <combustible>Gasolina</combustible>
    </coche>
</concesionario>
